### PR TITLE
Allows newer versions of composer/installers.

### PR DESCRIPTION
**Pull request by jeremyzahner**
Adds operator so newer versions of composer/installers are allowed.

### CODE REVIEW

**Comment by onnimonni** [comment]
Hey man! Nice to hear that you find this useful :)!,  thanks a lot.

**Comment by jeremyzahner** [comment]
@onnimonni Could you also release this? =)

**Comment by jeremyzahner** [comment]
@onnimonni Ping. =)

**Comment by onnimonni** [comment]
Sorry I don't work for devgeniem anymore and I can't.

@villesiltala can you do this?
```
$ cd /tmp/
$ git clone git@github.com:devgeniem/wp-sanitize-accented-uploads.git
$ cd wp-sanitize-accented-uploads
$ git tag 1.2.1
$ git push origin master --tags
```

**Comment by villesiltala** [comment]
@jeremyzahner, @onnimonni done! :)

**Comment by onnimonni** [comment]
thanks! @jeremyzahner Ping. =)

**Comment by jeremyzahner** [comment]
@villesiltala Thank you!

**Pull request merged**
